# Generated by Django 5.2 on 2025-04-19 10:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='bio',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
