# Generated by Django 5.2 on 2025-04-19 10:52

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_studentprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='bio',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
